# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: team.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nteam.proto\x12\x04team\"!\n\x11\x43reateTeamRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\"\x1d\n\x0fReadTeamRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x11UpdateTeamRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04task\x18\x02 \x01(\t\"\x1f\n\x11\x44\x65leteTeamRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteTeamResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x04Team\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04task\x18\x02 \x01(\t2\xd3\x01\n\x0bTeamService\x12-\n\x06\x43reate\x12\x17.team.CreateTeamRequest\x1a\n.team.Team\x12)\n\x04Read\x12\x15.team.ReadTeamRequest\x1a\n.team.Team\x12-\n\x06Update\x12\x17.team.UpdateTeamRequest\x1a\n.team.Team\x12;\n\x06\x44\x65lete\x12\x17.team.DeleteTeamRequest\x1a\x18.team.DeleteTeamResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'team_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATETEAMREQUEST']._serialized_start=20
  _globals['_CREATETEAMREQUEST']._serialized_end=53
  _globals['_READTEAMREQUEST']._serialized_start=55
  _globals['_READTEAMREQUEST']._serialized_end=84
  _globals['_UPDATETEAMREQUEST']._serialized_start=86
  _globals['_UPDATETEAMREQUEST']._serialized_end=131
  _globals['_DELETETEAMREQUEST']._serialized_start=133
  _globals['_DELETETEAMREQUEST']._serialized_end=164
  _globals['_DELETETEAMRESPONSE']._serialized_start=166
  _globals['_DELETETEAMRESPONSE']._serialized_end=203
  _globals['_TEAM']._serialized_start=205
  _globals['_TEAM']._serialized_end=237
  _globals['_TEAMSERVICE']._serialized_start=240
  _globals['_TEAMSERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
